clipboard_control write-clipboard write-primary read-clipboard read-primary

map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_keyboard

# Slight transparency
background_opacity 0.88
dynamic_background_opacity yes

# Auto colors from wal/wallust
include ~/.cache/matugen/colors-kitty.conf


# Font
font_family JetBrainsMono Nerd Font

# Cursor trail
cursor_trail 3

# Coffee cup on startup
on_launch sh -c 'printf "\n \033[36m) )\033[0m\n \033[36m( (\033[0m\n \033[37m╭───╮\033[0m\n \033[37m│ \033[30m▄\033[37m │─╮\033[0m\n \033[37m╰───╯─╯\033[0m\n\n"'
